[workspace]
members = [
    "crates/ast"    ,
    "crates/errors" ,
    "crates/lexer"  ,
    "crates/parser" ,
    "crates/runtime",
    "crates/cli"    ,
    "crates/jit"    ,
    "crates/codegen",
]
resolver = "2"
